server:
  port: 8443

spring:
  application:
    name: kd-geteway
  rabbitmq:
    host: ${RABBIT_MQ_HOST:rabbitmq-host}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:redis-host}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  #令牌桶的容积
            redis-rate-limiter.burstCapacity: 1  #流速 每秒
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
      routes:
        # =====================================
        - id: kd-admin
          uri: lb://kd-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=foo, bar
        - id: kd-auth
            uri: lb://kd-auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
              - AddResponseHeader=foo, bar

gate:
  ignore:
    authentication:
      startWith: /oauth,/open

management:
  endpoints:
    web:
      exposure:
        include: '*'

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

#  compression:
#    response:
#      enabled: true
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
logging:
  level:
    cn.otccloud.kingdom: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB
