zuul:
  routes:
    add-service-demo:
      path: /add-service/**
      serviceId: add-service
    random-service-demo:
      path: /random/**
      serviceId: random-service
spring:
  rabbitmq:
    host: 192.168.23.221
    port: 5672
    username: root
    password: kshop
