


server:
  port: 8100
  swagger-enable: true
spring:
  application:
    name: dinner-produce
  datasource:
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.23.223:3306/hyll_springboot?characterEncoding=utf-8
    username: root
    password: 123456
    validationQuery: SELECT 1 FROM DUAL
  sleuth:
    sampler:
      percentage: 0.1
  zipkin:
    base-url: http://localhost:9841
  rabbitmq:
    host: 192.168.23.221
    port: 5672
    username: root
    password: kshop
