server:
  port: 9841


spring:
  zipkin:
    base-url: http://localhost:9841
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.1.221
    port: 5672
    username: root
    password: kshop
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://192.168.1.223:3306/sleuth_log
    username: root
    password: 123456
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
  output:
    ansi:
      enabled: ALWAYS

zipkin:
  storage:
    type: mysql
